# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfautomv < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/busser/tfautomv"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/busser/tfautomv/releases/download/v0.6.0/tfautomv_0.6.0_darwin_arm64.tar.gz"
      sha256 "f1284cf4e7e6c12c72ee3f57109b856196eae3ebc722d532d4b8c2ed4da6499f"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tfautomv/releases/download/v0.6.0/tfautomv_0.6.0_darwin_amd64.tar.gz"
      sha256 "9d41d40e9d966fff686a043dec6e67c0c9d1cf7fd0e6eab96acadb0671e80c88"

      def install
        bin.install "tfautomv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/busser/tfautomv/releases/download/v0.6.0/tfautomv_0.6.0_linux_arm64.tar.gz"
      sha256 "7d4029c3c294c592231c13446bfeb376f657833cc47e34773dfe3593e233fa30"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tfautomv/releases/download/v0.6.0/tfautomv_0.6.0_linux_amd64.tar.gz"
      sha256 "d6c8542ad919fc657573721674a361d216edf22f43f85f364ce74aea5ace75c9"

      def install
        bin.install "tfautomv"
      end
    end
  end

  test do
    system "#{bin}/tfautomv -version"
  end
end
