# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfautomv < Formula
  desc "Display your Terraform module call stack"
  homepage "https://github.com/busser/tftree"
  version "0.1.0-rc2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc2/tftree_0.1.0-rc2_Darwin_arm64.tar.gz"
      sha256 "eec7fce6ebc87e491f6404ef97f1c306e0f1dfb8f648880419187295e929adac"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc2/tftree_0.1.0-rc2_Darwin_x86_64.tar.gz"
      sha256 "265061e33d4e78570eadf22fd433a9e754e1306faa3536a0e33a7d1b556f4810"

      def install
        bin.install "tftree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc2/tftree_0.1.0-rc2_Linux_arm64.tar.gz"
      sha256 "9036dd0bc5856bce77a210064a18bd3165e6704e5d55fb29383dcc42bd622aca"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc2/tftree_0.1.0-rc2_Linux_x86_64.tar.gz"
      sha256 "eae1a5be075255f223a5df9a44577c05d59679e7a205de2b8ac814acfeae7783"

      def install
        bin.install "tftree"
      end
    end
  end

  test do
    system "#{bin}/tftree -version"
  end
end
