# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftree < Formula
  desc "Display your Terraform module call stack"
  homepage "https://github.com/busser/tftree"
  version "0.1.0-rc3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc3/tftree_0.1.0-rc3_Darwin_arm64.tar.gz"
      sha256 "8cb6a2b8b96223f047c3a538cdaee45fec4e7a377cb20663e46b083862354089"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc3/tftree_0.1.0-rc3_Darwin_x86_64.tar.gz"
      sha256 "ad6373daf916a0e53551554363e965f8a8ef8f617643947c38ab7b55311fe48e"

      def install
        bin.install "tftree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc3/tftree_0.1.0-rc3_Linux_arm64.tar.gz"
      sha256 "ed2071080aabb224a42631226e51879045d4c0e9c18bddd275ca64e7cedaf570"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0-rc3/tftree_0.1.0-rc3_Linux_x86_64.tar.gz"
      sha256 "81c98e1517ab3aad5b8869bfda4cf14bab4d56faec8c6b26a9407dfb0f40cf42"

      def install
        bin.install "tftree"
      end
    end
  end

  test do
    system "#{bin}/tftree -version"
  end
end
