# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftree < Formula
  desc "Display your Terraform module call stack"
  homepage "https://github.com/busser/tftree"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/busser/tftree/releases/download/v0.1.0/tftree_0.1.0_Darwin_arm64.tar.gz"
      sha256 "21ba24074c79b63bbd2e50e0fa885afa85175632b0b5678f42661b284299b923"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0/tftree_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ceb5aaca6077ca57ed106ecdde1f8d038c3f663309fd998f165bfea27047fb52"

      def install
        bin.install "tftree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/busser/tftree/releases/download/v0.1.0/tftree_0.1.0_Linux_arm64.tar.gz"
      sha256 "dacacd2229fc6b2cf3c3bf714fb88d9d3b25c8b62a70e04c5d1fca87c566382d"

      def install
        bin.install "tftree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/busser/tftree/releases/download/v0.1.0/tftree_0.1.0_Linux_x86_64.tar.gz"
      sha256 "5d9ae8bb79ee028fe2c5b3bdb47b510842370e5c676850906adf654597a8fc23"

      def install
        bin.install "tftree"
      end
    end
  end

  test do
    system "#{bin}/tftree -version"
  end
end
